const { firefox } = require('playwright');
(async ()=>{
  const browser = await firefox.launch();
  const page = await browser.newPage();
  await page.goto('http://localhost:8000');
  await page.waitForTimeout(400);
  await page.evaluate(()=>{ window.FileManager && window.FileManager.write('testfile.py','# test file') });
  await page.waitForTimeout(200);
  await page.click('#file-refresh');
  await page.waitForTimeout(200);
  const openBtn = await page.$('#files-list button');
  if(openBtn) await openBtn.click();
  await page.waitForTimeout(200);
  const tabs = await page.$$eval('.tab .tab-label', els=>els.map(e=>e.textContent));
  console.log('tabs before edit:', tabs);
  await page.evaluate(()=>{ if(window.cm) window.cm.setValue('# edited test file'); else document.getElementById('code').value = '# edited test file' });
  await page.waitForTimeout(900);
  const raw = await page.evaluate(()=> localStorage.getItem('ssg_files_v1'));
  console.log('local after edit:', raw);
  await browser.close();
})();
